In [ ]:
import numpy as np
import pandas as pd
from collections import defaultdict
from sklearn.cluster import KMeans

## EDA

In [157]:
dataset = pd.read_csv("../datasets/imdb_top_1000.csv")
dataset.iloc[1:5, :]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [158]:
dataset.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

### String Cleaning

In [159]:
dataset['Runtime'] = dataset['Runtime'].str.removesuffix(' min').astype('int64')
dataset['Gross'] = dataset['Gross'].str.replace(',', '')
dataset.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000

### Fixing Gross

In [160]:
print(f"NaN in 'Gross' before: {np.size(dataset[dataset['Gross'].isna()])}")
dataset['Gross'] = dataset['Gross'].replace(np.nan, 0)
print(f"NaN in 'Gross' after: {np.size(dataset[dataset['Gross'].isna()])}")
dataset['Gross'] = dataset['Gross'].astype('int64')

NaN in 'Gross' before: 2704
NaN in 'Gross' after: 0

### Dict of Genres

In [161]:
genre = defaultdict(list)
for idx, genres in enumerate(dataset['Genre']):
    for y in genres.split(','):
        genre[y.strip()].append(dataset.iloc[idx]['Series_Title'])

genre

defaultdict(list,
            {'Drama': ['The Shawshank Redemption',
              'The Godfather',
              'The Dark Knight',
              'The Godfather: Part II',
              '12 Angry Men',
              'The Lord of the Rings: The Return of the King',
              'Pulp Fiction',
              "Schindler's List",
              'Fight Club',
              'The Lord of the Rings: The Fellowship of the Ring',
              'Forrest Gump',
              'The Lord of the Rings: The Two Towers',
              'Goodfellas',
              "One Flew Over the Cuckoo's Nest",
              'Hamilton',
              'Gisaengchung',
              'Soorarai Pottru',
              'Interstellar',
              'Cidade de Deus',
              'Saving Private Ryan',
              'The Green Mile',
              'La vita è bella',
              'Se7en',
              'The Silence of the Lambs',
              'Seppuku',
              'Shichinin no samurai',
              "It's a Wonderful Life",
              'Joker',
              'Whiplash',
              'The Intouchables',
              'The Prestige',
              'The Departed',
              'The Pianist',
              'Gladiator',
              'American History X',
              'Léon',
              'The Lion King',
              'Nuovo Cinema Paradiso',
              'Hotaru no haka',
              'Casablanca',
              'Modern Times',
              'City Lights',
              'Capharnaüm',
              'Ayla: The Daughter of War',
              'Vikram Vedha',
              'Kimi no na wa.',
              'Dangal',
              'Avengers: Endgame',
              'Django Unchained',
              '3 Idiots',
              'Taare Zameen Par',
              'The Lives of Others',
              'Oldeuboi',
              'Once Upon a Time in America',
              'The Shining',
              'Apocalypse Now',
              'Anand',
              'Tengoku to jigoku',
              'Witness for the Prosecution',
              'Paths of Glory',
              'Sunset Blvd.',
              'The Great Dictator',
              '1917',
              'Tumbbad',
              'Andhadhun',
              'Drishyam',
              'Jagten',
              'Jodaeiye Nader az Simin',
              'Incendies',
              'Miracle in cell NO.7',
              'Babam ve Oglum',
              'Inglourious Basterds',
              'Eternal Sunshine of the Spotless Mind',
              'Requiem for a Dream',
              'American Beauty',
              'Good Will Hunting',
              'Bacheha-Ye aseman',
              'Braveheart',
              'Reservoir Dogs',
              'Full Metal Jacket',
              'Idi i smotri',
              'Amadeus',
              'Scarface',
              'Das Boot',
              'Taxi Driver',
              'The Sting',
              'A Clockwork Orange',
              'Lawrence of Arabia',
              'The Apartment',
              'Ikiru',
              'Ladri di biciclette',
              'Double Indemnity',
              'Citizen Kane',
              'Metropolis',
              'The Kid',
              'Chhichhore',
              'Uri: The Surgical Strike',
              'K.G.F: Chapter 1',
              'Green Book',
              'Three Billboards Outside Ebbing, Missouri',
              'Talvar',
              'Baahubali 2: The Conclusion',
              'Drishyam',
              'Queen',
              'Mandariinid',
              'Bhaag Milkha Bhaag',
              'Udaan',
              'El secreto de sus ojos',
              'Warrior',
              'The Wolf of Wall Street',
              'Chak De! India',
              'There Will Be Blood',
              "Pan's Labyrinth",
              'V for Vendetta',
              'Rang De Basanti',
              'Black',
              'Swades: We, the People',
              'Der Untergang',
              'A Beautiful Mind',
              'L.A. Confidential',
              'Eskiya',
              'Heat',
              'Casino',
              'Unforgiven',
              'Dom za vesanje',
              'Ran',
              'Raging Bull',
              'Stalker',
              'Höstsonaten',
              'The Message',
              'The Great Escape',
              'To Kill a Mockingbird',
              'Yôjinbô',
              'Judgment at Nuremberg',
              'Smultronstället',
              'Det sjunde inseglet',
              'Du rififi chez les hommes',
              'Tôkyô monogatari',
              'Rashômon',
              'All About Eve',
              'The Treasure of the Sierra Madre',
              'The Gold Rush',
              'Portrait de la jeune fille en feu',
              'Pink',
              'Koe no katachi',
              'Contratiempo',
              'Ah-ga-ssi',
              'Mommy',
              'Haider',
              'Logan',
              'Room',
              'Relatos salvajes',
              'Kis Uykusu',
              'PK',
              'OMG: Oh My God!',
              'Gone Girl',
              'Ôkami kodomo no Ame to Yuki',
              'Hacksaw Ridge',
              'Barfi!',
              '12 Years a Slave',
              'Rush',
              'Ford v Ferrari',
              'Spotlight',
              'Song of the Sea',
              'Zindagi Na Milegi Dobara',
              'Prisoners',
              'A Wednesday',
              'Gran Torino',
              'Harry Potter and the Deathly Hallows: Part 2',
              'Okuribito',
              "Hachi: A Dog's Tale",
              'Mary and Max',
              'Into the Wild',
              'No Country for Old Men',
              'Lage Raho Munna Bhai',
              'Million Dollar Baby',
              'Hotel Rwanda',
              'Taegukgi hwinalrimyeo',
              'Before Sunset',
              'Munna Bhai M.B.B.S.',
              'Salinui chueok',
              'Dil Chahta Hai',
              'Kill Bill: Vol. 1',
              'Catch Me If You Can',
              'Amores perros',
              'Shin seiki Evangelion Gekijô-ban: Air/Magokoro wo, kimi ni',
              'Lagaan: Once Upon a Time in India',
              'The Sixth Sense',
              "La leggenda del pianista sull'oceano",
              'The Truman Show',
              'Fa yeung nin wah',
              'Trainspotting',
              'Fargo',
              'Underground',
              'La haine',
              'Dilwale Dulhania Le Jayenge',
              'Before Sunrise',
              'Trois couleurs: Rouge',
              'Chung Hing sam lam',
              'In the Name of the Father',
              'Ba wang bie ji',
              'Dà hóng denglong gaogao guà',
              'Dead Poets Society',
              'Stand by Me',
              'Platoon',
              'Paris, Texas',
              'Pink Floyd: The Wall',
              'Fitzcarraldo',
              'Fanny och Alexander',
              'The Elephant Man',
              'The Deer Hunter',
              'Rocky',
              'Network',
              'Barry Lyndon',
              'Zerkalo',
              'Chinatown',
              'Paper Moon',
              'Viskningar och rop',
              'Solaris',
              'Le samouraï',
              'Cool Hand Luke',
              'Persona',
              'Andrei Rublev',
              'La battaglia di Algeri',
              'El ángel exterminador',
              'What Ever Happened to Baby Jane?',
              'The Man Who Shot Liberty Valance',
              'Ivanovo detstvo',
              'Jungfrukällan',
              'Inherit the Wind',
              'Les quatre cents coups',
              'Ben-Hur',
              'Kakushi-toride no san-akunin',
              'Le notti di Cabiria',
              'Kumonosu-jô',
              'The Bridge on the River Kwai',
              'On the Waterfront',
              'Le salaire de la peur',
              'Ace in the Hole',
              'White Heat',
              'The Red Shoes',
              'The Shop Around the Corner',
              'Rebecca',
              'Mr. Smith Goes to Washington',
              'Gone with the Wind',
              'La Grande Illusion',
              "La passion de Jeanne d'Arc",
              'Sunrise: A Song of Two Humans',
              'Badhaai ho',
              'Togo',
              'Airlift',
              'La La Land',
              'Lion',
              'The Martian',
              'Bãhubali: The Beginning',
              'Kaguyahime no monogatari',
              'Wonder',
              'Gully Boy',
              'Special Chabbis',
              'Short Term 12',
              'The Imitation Game',
              'Blade Runner 2049',
              'Her',
              'Bohemian Rhapsody',
              'The Revenant',
              'The Perks of Being a Wallflower',
              'Tropa de Elite 2: O Inimigo Agora é Outro',
              "The King's Speech",
              'The Help',
              'Darbareye Elly',
              'Dev.D',
              'Yip Man',
              'My Name Is Khan',
              'Nefes: Vatan Sagolsun',
              'Slumdog Millionaire',
              'Black Swan',
              'Tropa de Elite',
              'Persepolis',
              'Dallas Buyers Club',
              'The Pursuit of Happyness',
              'Blood Diamond',
              'Bin-jip',
              'Le scaphandre et le papillon',
              'Vozvrashchenie',
              'Bom Yeoareum Gaeul Gyeoul Geurigo Bom',
              'Mar adentro',
              'Cinderella Man',
              'Kal Ho Naa Ho',
              'Mou gaan dou',
              'Big Fish',
              'Yeopgijeogin geunyeo',
              'Dogville',
              'Vizontele',
              'Donnie Darko',
              'Magnolia',
              'Dancer in the Dark',
              'The Straight Story',
              'Festen',
              'Central do Brasil',
              'Sling Blade',
              'Secrets & Lies',
              'Bound by Honor',
              'Scent of a Woman',
              'JFK',
              'Dances with Wolves',
              'Do the Right Thing',
              'Rain Man',
              'Der Himmel über Berlin',
              'Au revoir les enfants',
              'Tenkû no shiro Rapyuta',
              'Gandhi',
              'Kagemusha',
              'Being There',
              'Dog Day Afternoon',
              'Papillon',
              'The Last Picture Show',
              'Fiddler on the Roof',
              'Il conformista',
              'Butch Cassidy and the Sundance Kid',
              "Rosemary's Baby",
              'The Graduate',
              "Who's Afraid of Virginia Woolf?",
              'The Sound of Music',
              'Doctor Zhivago',
              'Per un pugno di dollari',
              '8½',
              'Vivre sa vie: Film en douze tableaux',
              'The Hustler',
              'La dolce vita',
              'Rio Bravo',
              'Anatomy of a Murder',
              'Touch of Evil',
              'Cat on a Hot Tin Roof',
              'Sweet Smell of Success',
              'The Killing',
              'The Night of the Hunter',
              'La Strada',
              'Les diaboliques',
              'Stalag 17',
              'A Streetcar Named Desire',
              'In a Lonely Place',
              'Rope',
              'Out of the Past',
              'Brief Encounter',
              'Laura',
              'The Best Years of Our Lives',
              'The Grapes of Wrath',
              'La règle du jeu',
              'All Quiet on the Western Front',
              'Bronenosets Potemkin',
              'Knives Out',
              'Dil Bechara',
              'Manbiki kazoku',
              'Marriage Story',
              'Call Me by Your Name',
              'I, Daniel Blake',
              'Hunt for the Wilderpeople',
              'Captain Fantastic',
              'Sing Street',
              'Nightcrawler',
              'Jojo Rabbit',
              'Arrival',
              'Before Midnight',
              "Bir Zamanlar Anadolu'da",
              'The Artist',
              'Amour',
              'The Irishman',
              'Un prophète',
              'Moon',
              'Låt den rätte komma in',
              'The Wrestler',
              'Jab We Met',
              'Boyhood',
              '4 luni, 3 saptamâni si 2 zile',
              'In Bruges',
              'The Man from Earth',
              'Letters from Iwo Jima',
              'The Fall',
              'Life of Pi',
              'C.R.A.Z.Y.',
              'Les choristes',
              'Gegen die Wand',
              'Mystic River',
              'Hable con ella',
              "No Man's Land",
              'Nueve reinas',
              'Children of Men',
              'Almost Famous',
              'Mulholland Dr.',
              'Boogie Nights',
              'Mimi wo sumaseba',
              'Once Were Warriors',
              'True Romance',
              'Trois couleurs: Bleu',
              "Carlito's Way",
              'Edward Scissorhands',
              'My Left Foot: The Story of Christy Brown',
              'Crimes and Misdemeanors',
              'The Untouchables',
              'Hannah and Her Sisters',
              'Brazil',
              'Manhattan',
              'All That Jazz',
              "All the President's Men",
              'La montaña sagrada',
              'Amarcord',
              'Harold and Maude',
              'Patton',
              'The Lion in Winter',
              'In the Heat of the Night',
              'The Manchurian Candidate',
              'Spartacus',
              "L'avventura",
              'Hiroshima mon amour',
              'The Ten Commandments',
              'The Searchers',
              'East of Eden',
              'High Noon',
              'Harvey',
              'Miracle on 34th Street',
              'Notorious',
              'The Lost Weekend',
              'His Girl Friday',
              'Freaks',
              'Raazi',
              'Sound of Metal',
              'Forushande',
              'Dunkirk',
              'Perfetti sconosciuti',
              'Hidden Figures',
              'Udta Punjab',
              'M.S. Dhoni: The Untold Story',
              'Manchester by the Sea',
              'Under sandet',
              'The Hateful Eight',
              'Little Women',
              'Pride',
              'Le passé',
              'La grande bellezza',
              'The Lunchbox',
              'About Time',
              'English Vinglish',
              'Kaze tachinu',
              'La migliore offerta',
              'Moonrise Kingdom',
              'The Big Short',
              'Kokuhaku',
              'Ang-ma-reul bo-at-da',
              'The Girl with the Dragon Tattoo',
              'Ajeossi',
              'Straight Outta Compton',
              'Madeo',
              'Das weiße Band - Eine deutsche Kindergeschichte',
              'Män som hatar kvinnor',
              'The Trial of the Chicago 7',
              'Druk',
              'The Fighter',
              'The Boy in the Striped Pyjamas',
              'Once',
              'Auf der anderen Seite',
              'Atonement',
              'Drive',
              'American Gangster',
              'Mr. Nobody',
              'Apocalypto',
              'Little Miss Sunshine',
              'The Curious Case of Benjamin Button',
              'Veer-Zaara',
              'Adams æbler',
              'Pride & Prejudice',
              "The World's Fastest Indian",
              'Walk the Line',
              'Ondskan',
              'The Notebook',
              'Diarios de motocicleta',
              'Lilja 4-ever',
              'Les triplettes de Belleville',
              'Gongdong gyeongbi guyeok JSA',
              'The Count of Monte Cristo',
              'Waking Life',
              'Remember the Titans',
              'Todo sobre mi madre',
              'Cast Away',
              'The Insider',
              'October Sky',
              'Titanic',
              'Hana-bi',
              'Gattaca',
              'The Game',
              'Breaking the Waves',
              'Ed Wood',
              "What's Eating Gilbert Grape",
              'Tombstone',
              'The Sandlot',
              'The Remains of the Day',
              'Naked',
              'The Fugitive',
              'A Bronx Tale',
              'Night on Earth',
              'La double vie de Véronique',
              'Boyz n the Hood',
              'Misery',
              'Awakenings',
              'Majo no takkyûbin',
              'Glory',
              'Dip huet seung hung',
              'Mississippi Burning',
              'Down by Law',
              'The Color Purple',
              'The Breakfast Club',
              'The Killing Fields',
              'The Right Stuff',
              'The King of Comedy',
              'Kramer vs. Kramer',
              'Days of Heaven',
              'The Conversation',
              'The Day of the Jackal',
              'Badlands',
              'Cabaret',
              'Midnight Cowboy',
              "Guess Who's Coming to Dinner",
              'My Fair Lady',
              'The Longest Day',
              'Jules et Jim',
              'À bout de souffle',
              'Red River',
              'Key Largo',
              'Stagecoach',
              'Bride of Frankenstein',
              'Scarface: The Shame of the Nation',
              'Frankenstein',
              'Roma',
              "God's Own Country",
              'Wind River',
              'En man som heter Ove',
              'Omoide no Mânî',
              'The Theory of Everything',
              'The Fault in Our Stars',
              'Me and Earl and the Dying Girl',
              'Birdman or (The Unexpected Virtue of Ignorance)',
              "La vie d'Adèle",
              'Kai po che!',
              'The Broken Circle Breakdown',
              'Rockstar',
              'Nebraska',
              'Le Petit Prince',
              'Detachment',
              'Gravity',
              'Beasts of No Nation',
              'The Social Network',
              'Silver Linings Playbook',
              'Argo',
              '(500) Days of Summer',
              'Frost/Nixon',
              'Papurika',
              'Changeling',
              'Flipped',
              'Death Note: Desu nôto',
              'This Is England',
              'Ex Machina',
              'Efter brylluppet',
              'The Last King of Scotland',
              'Zodiac',
              'Lucky Number Slevin',
              'Joyeux Noël',
              'Control',
              'Zwartboek',
              'Brokeback Mountain',
              '3:10 to Yuma',
              'Crash',
              'The Machinist',
              'Ray',
              'Lost in Translation',
              'Man on Fire',
              'Coraline',
              'The Last Samurai',
              'The Magdalene Sisters',
              'Good Bye Lenin!',
              'In America',
              'I Am Sam',
              'Adaptation.',
              'Black Hawk Down',
              'Road to Perdition',
              'Das Experiment',
              'Billy Elliot',
              'Hedwig and the Angry Inch',
              'Interstate 60: Episodes of the Road',
              'Happiness',
              'Training Day',
              'Rushmore',
              'Abre los ojos',
              'Being John Malkovich',
              'As Good as It Gets',
              'Donnie Brasco',
              'Shine',
              'Primal Fear',
              'Hamlet',
              'A Little Princess',
              'Do lok tin si',
              'Il postino',
              'Short Cuts',
              'Philadelphia',
              'The Muppet Christmas Carol',
              'Malcolm X',
              'The Last of the Mohicans',

### Genre counts

In [162]:
for g in set(genre.keys()):
    dataset[g] = dataset['Genre'].apply(lambda x: 1 if g in x.strip() else 0)

In [172]:
dataset.loc[:, list(genre.keys())].sum()

Drama        724
Crime        209
Action       189
Adventure    196
Biography    109
History       56
Sci-Fi        67
Romance      125
Western       20
Fantasy       66
Comedy       233
Thriller     137
Animation     82
Family        56
War           51
Mystery       99
Music         47
Horror        32
Musical       17
Film-Noir     19
Sport         19
dtype: int64

### Weighted Avg to Supplement Missing Meta Scores

In [173]:
ratings = dataset['IMDB_Rating'].values
votes = dataset['No_of_Votes'].values
dataset['Weighted_Avg'] = (ratings * votes + votes.min() * ratings.mean()) / (votes + votes.min())
dataset.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,...,Crime,Music,War,Musical,Horror,Fantasy,Action,Adventure,Biography,Weighted_Avg
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,...,0,0,0,0,0,0,0,0,0,9.285691
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,...,1,0,0,0,0,0,0,0,0,9.180931
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,...,1,0,0,0,0,0,1,0,0,8.988679
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,...,1,0,0,0,0,0,0,0,0,8.977178
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,...,1,0,0,0,0,0,0,0,0,8.963129

### Dataset describe

In [174]:
dataset.describe()

,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross,Drama,Western,Comedy,Romance,Sport,...,Crime,Music,War,Musical,Horror,Fantasy,Action,Adventure,Biography,Weighted_Avg
count,1000.000000,1000.000000,843.000000,1.000000e+03,1.000000e+03,1000.00000,1000.00000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,122.891000,7.949300,77.971530,2.736929e+05,5.653688e+07,0.72400,0.02000,0.233000,0.125000,0.019000,...,0.209000,0.047000,0.051000,0.017000,0.032000,0.066000,0.189000,0.196000,0.109000,7.957808
std,28.093671,0.275491,12.376099,3.273727e+05,1.032382e+08,0.44724,0.14007,0.422954,0.330884,0.136593,...,0.406798,0.211745,0.220108,0.129336,0.176088,0.248406,0.391705,0.397167,0.311795,0.242824
min,45.000000,7.600000,28.000000,2.508800e+04,0.000000e+00,0.00000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.611562
25%,103.000000,7.700000,70.000000,5.552625e+04,4.457098e+05,0.00000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.799293
50%,119.000000,7.900000,79.000000,1.385485e+05,1.070275e+07,1.00000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.913042
75%,137.000000,8.100000,87.000000,3.741612e+05,6.153989e+07,1.00000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.077983
max,321.000000,9.300000,100.000000,2.343110e+06,9.366622e+08,1.00000,1.00000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.285691

## ML stuff

In [ ]:
height = dataset.shape[0]
train_X = dataset.iloc[:int(.8*height)]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,...,Crime,Music,War,Musical,Horror,Fantasy,Action,Adventure,Biography,Weighted_Avg
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,...,0,0,0,0,0,0,0,0,0,9.285691
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,...,1,0,0,0,0,0,0,0,0,9.180931
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,...,1,0,0,0,0,0,1,0,0,8.988679
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,...,1,0,0,0,0,0,0,0,0,8.977178
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,...,1,0,0,0,0,0,0,0,0,8.963129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,https://m.media-amazon.com/images/M/MV5BYzVmYz...,Ocean's Eleven,2001,UA,116,"Crime, Thriller",7.7,Danny Ocean and his ten accomplices plan to ro...,74.0,Steven Soderbergh,...,1,0,0,0,0,0,0,0,0,7.711551
796,https://m.media-amazon.com/images/M/MV5BNTIyNT...,Vampire Hunter D: Bloodlust,2000,U,103,"Animation, Action, Fantasy",7.7,"When a girl is abducted by a vampire, a legend...",62.0,Yoshiaki Kawajiri,...,0,0,0,0,0,1,1,0,0,7.815187
797,https://m.media-amazon.com/images/M/MV5BMjZkOT...,"O Brother, Where Art Thou?",2000,U,107,"Adventure, Comedy, Crime",7.7,"In the deep south during the 1930s, three esca...",69.0,Joel Coen,...,1,0,0,0,0,0,0,1,0,7.720057
798,https://m.media-amazon.com/images/M/MV5BZDYwYz...,Interstate 60: Episodes of the Road,2002,R,116,"Adventure, Comedy, Drama",7.7,"Neal Oliver, a very confused young man and an ...",NaN,Bob Gale,...,0,0,0,0,0,0,0,1,0,7.813537
799,https://m.media-amazon.com/images/M/MV5BOGE0ZW...,"South Park: Bigger, Longer & Uncut",1999,A,81,"Animation, Comedy, Fantasy",7.7,When Stan Marsh and his friends go see an R-ra...,73.0,Trey Parker,...,0,0,0,0,0,1,0,0,0,7.728796