In [119]:
import numpy as np
import pandas as pd
from collections import defaultdict

## EDA

In [120]:
dataset = pd.read_csv("../datasets/imdb_top_1000.csv")
dataset.iloc[1:5, :]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [121]:
dataset.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

### String Cleaning

In [122]:
dataset['Runtime'] = dataset['Runtime'].str.removesuffix(' min').astype('int64')
dataset['Gross'] = dataset['Gross'].str.replace(',', '')
dataset.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000

### Fixing Gross

In [123]:
print(f"NaN in 'Gross' before: {np.size(dataset[dataset['Gross'].isna()])}")
dataset['Gross'] = dataset['Gross'].replace(np.nan, 0)
print(f"NaN in 'Gross' after: {np.size(dataset[dataset['Gross'].isna()])}")
dataset['Gross'] = dataset['Gross'].astype('int64')

NaN in 'Gross' before: 2704
NaN in 'Gross' after: 0

### Dict of Genres

In [124]:
genre = defaultdict(list)
for idx, genres in enumerate(dataset['Genre']):
    for y in genres.split(','):
        genre[y].append(dataset.iloc[idx]['Series_Title'])

genre

defaultdict(list,
            {'Drama': ['The Shawshank Redemption',
              'Fight Club',
              'Forrest Gump',
              "One Flew Over the Cuckoo's Nest",
              'Soorarai Pottru',
              'Saving Private Ryan',
              "It's a Wonderful Life",
              'Whiplash',
              'The Prestige',
              'American History X',
              'Nuovo Cinema Paradiso',
              'Casablanca',
              'Capharnaüm',
              'Django Unchained',
              'Taare Zameen Par',
              'The Lives of Others',
              'The Shining',
              'Apocalypse Now',
              'Anand',
              'Paths of Glory',
              'Sunset Blvd.',
              '1917',
              'Tumbbad',
              'Jagten',
              'Jodaeiye Nader az Simin',
              'Incendies',
              'Miracle in cell NO.7',
              'Babam ve Oglum',
              'Eternal Sunshine of the Spotless Mind',
              'Requiem for a Dream',
              'American Beauty',
              'Good Will Hunting',
              'Bacheha-Ye aseman',
              'Full Metal Jacket',
              'Idi i smotri',
              'Ikiru',
              'Ladri di biciclette',
              'Citizen Kane',
              'Metropolis',
              'Mandariinid',
              'Udaan',
              'El secreto de sus ojos',
              'Chak De! India',
              'There Will Be Blood',
              "Pan's Labyrinth",
              'Black',
              'Swades: We, the People',
              'Unforgiven',
              'Stalker',
              'Höstsonaten',
              'Judgment at Nuremberg',
              'Smultronstället',
              'Det sjunde inseglet',
              'Tôkyô monogatari',
              'All About Eve',
              'Portrait de la jeune fille en feu',
              'Pink',
              'Ah-ga-ssi',
              'Mommy',
              'Room',
              'Kis Uykusu',
              'Gone Girl',
              'Gran Torino',
              'Okuribito',
              'Million Dollar Baby',
              'Before Sunset',
              'Amores perros',
              'The Sixth Sense',
              "La leggenda del pianista sull'oceano",
              'Fa yeung nin wah',
              'Trainspotting',
              'Dilwale Dulhania Le Jayenge',
              'Before Sunrise',
              'Trois couleurs: Rouge',
              'Ba wang bie ji',
              'Dà hóng denglong gaogao guà',
              'Platoon',
              'Paris, Texas',
              'Pink Floyd: The Wall',
              'Fanny och Alexander',
              'The Deer Hunter',
              'Rocky',
              'Network',
              'Chinatown',
              'Viskningar och rop',
              'Solaris',
              'Persona',
              'La battaglia di Algeri',
              'El ángel exterminador',
              'What Ever Happened to Baby Jane?',
              'The Man Who Shot Liberty Valance',
              'Ivanovo detstvo',
              'Jungfrukällan',
              'Le notti di Cabiria',
              'Kumonosu-jô',
              'Ace in the Hole',
              'The Red Shoes',
              'Rebecca',
              'Gone with the Wind',
              'La Grande Illusion',
              'Sunrise: A Song of Two Humans',
              'Airlift',
              'Wonder',
              'Gully Boy',
              'Short Term 12',
              'Her',
              'The Perks of Being a Wallflower',
              'The Help',
              'Darbareye Elly',
              'Dev.D',
              'My Name Is Khan',
              'Slumdog Millionaire',
              'Black Swan',
              'Vozvrashchenie',
              'Bom Yeoareum Gaeul Gyeoul Geurigo Bom',
              'Donnie Darko',
              'Magnolia',
              'Festen',
              'Central do Brasil',
              'Sling Blade',
              'Scent of a Woman',
              'JFK',
              'Rain Man',
              'Der Himmel über Berlin',
              'Au revoir les enfants',
              'Kagemusha',
              'The Last Picture Show',
              'Fiddler on the Roof',
              'Il conformista',
              "Rosemary's Baby",
              "Who's Afraid of Virginia Woolf?",
              'Doctor Zhivago',
              '8½',
              'Vivre sa vie: Film en douze tableaux',
              'The Hustler',
              'Cat on a Hot Tin Roof',
              'Sweet Smell of Success',
              'La Strada',
              'A Streetcar Named Desire',
              'In a Lonely Place',
              'Brief Encounter',
              'Laura',
              'The Best Years of Our Lives',
              'The Grapes of Wrath',
              'All Quiet on the Western Front',
              'Bronenosets Potemkin',
              'Call Me by Your Name',
              'I, Daniel Blake',
              'Arrival',
              'Before Midnight',
              'Amour',
              'Moon',
              'The Wrestler',
              'Boyhood',
              '4 luni, 3 saptamâni si 2 zile',
              'The Man from Earth',
              'Les choristes',
              'Gegen die Wand',
              'Hable con ella',
              'Mulholland Dr.',
              'Boogie Nights',
              'Trois couleurs: Bleu',
              'Edward Scissorhands',
              'Brazil',
              'All That Jazz',
              'The Manchurian Candidate',
              "L'avventura",
              'Hiroshima mon amour',
              'East of Eden',
              'High Noon',
              'Notorious',
              'The Lost Weekend',
              'Freaks',
              'Sound of Metal',
              'Forushande',
              'Manchester by the Sea',
              'Under sandet',
              'Little Women',
              'Le passé',
              'La grande bellezza',
              'The Lunchbox',
              'Kokuhaku',
              'Das weiße Band - Eine deutsche Kindergeschichte',
              'The Trial of the Chicago 7',
              'The Boy in the Striped Pyjamas',
              'Once',
              'Auf der anderen Seite',
              'Atonement',
              'Mr. Nobody',
              'The Curious Case of Benjamin Button',
              'Veer-Zaara',
              'Pride & Prejudice',
              'Ondskan',
              'The Notebook',
              'Todo sobre mi madre',
              'Titanic',
              'Gattaca',
              'Breaking the Waves',
              "What's Eating Gilbert Grape",
              'The Remains of the Day',
              'La double vie de Véronique',
              'Misery',
              'The Color Purple',
              'Kramer vs. Kramer',
              'Days of Heaven',
              'The Conversation',
              'Cabaret',
              'Midnight Cowboy',
              'My Fair Lady',
              'Jules et Jim',
              'Bride of Frankenstein',
              'Frankenstein',
              'Roma',
              "God's Own Country",
              'The Fault in Our Stars',
              "La vie d'Adèle",
              'Kai po che!',
              'The Broken Circle Breakdown',
              'Rockstar',
              'Detachment',
              'Gravity',
              'Beasts of No Nation',
              'Ex Machina',
              'Efter brylluppet',
              'Joyeux Noël',
              'Zwartboek',
              'Brokeback Mountain',
              'The Machinist',
              'The Magdalene Sisters',
              'In America',
              'I Am Sam',
              'Black Hawk Down',
              'Das Experiment',
              'Billy Elliot',
              'Abre los ojos',
              'Hamlet',
              'A Little Princess',
              'Philadelphia',
              'A Few Good Men',
              'Fried Green Tomatoes',
              'Blue Velvet',
              'The Verdict',
              'Ordinary People',
              'Le locataire',
              'Belle de jour',
              'Repulsion',
              'Zulu',
              'The Birds',
              'Cape Fear',
              'Peeping Tom',
              'Les yeux sans visage',
              'Invasion of the Body Snatchers',
              'Rebel Without a Cause',
              'The Day the Earth Stood Still',
              'Gilda',
              'Searching',
              'Nelyubov',
              'The Florida Project',
              'Gifted',
              'Mustang',
              'Bridge of Spies',
              'Creed',
              'A Star Is Born',
              'True Grit',
              'Hævnen',
              'La piel que habito',
              'Die Welle',
              'The Visitor',
              'Seven Pounds',
              'The Illusionist',
              'Match Point',
              'Synecdoche, New York',
              'Mysterious Skin',
              'Un long dimanche de fiançailles',
              '25th Hour',
              'The Butterfly Effect',
              '28 Days Later...',
              'Y tu mamá también',
              'Enemy at the Gates',
              'The Thin Red Line',
              'Sense and Sensibility',
              'The Bridges of Madison County',
              'On Golden Pond',
              'Close Encounters of the Third Kind',
              'Giù la testa',
              'Blowup',
              'Giant',
              'From Here to Eternity',
              'Lifeboat'],
             'Crime': ['The Godfather',
              'The Godfather: Part II',
              '12 Angry Men',
              'Pulp Fiction',
              'Cidade de Deus',
              'The Green Mile',
              'Se7en',
              'The Silence of the Lambs',
              'Joker',
              'The Departed',
              'The Usual Suspects',
              'Once Upon a Time in America',
              'Tengoku to jigoku',
              'Witness for the Prosecution',
              'Andhadhun',
              'Drishyam',
              'Reservoir Dogs',
              'Scarface',
              'Taxi Driver',
              'A Clockwork Orange',
              'Double Indemnity',
              'M - Eine Stadt sucht einen Mörder',
              'Talvar',
              'Drishyam',
              'L.A. Confidential',
              'Eskiya',
              'Heat',
              'Casino',
              'To Kill a Mockingbird',
              'Du rififi chez les hommes',
              'Dial M for Murder',
              'Rashômon',
              'Contratiempo',
              'Prisoners',
              'No Country for Old Men',
              'Salinui chueok',
              'Fargo',
              'La haine',
              'Le samouraï',
              'Cool Hand Luke',
              'Les quatre cents coups',
              'On the Waterfront',
              'Special Chabbis',
              'Bin-jip',
              'Sin City',
              'Dogville',
              'Dancer in the Dark',
              'Bound by Honor',
              'Anatomy of a Murder',
              'Touch of Evil',
              'The Killing',
              'The Night of the Hunter',
              'Les diaboliques',
              'Rope',
              'Out of the Past',
              'Manbiki kazoku',
              'Nightcrawler',
              "Bir Zamanlar Anadolu'da",
              'Un prophète',
              'Låt den rätte komma in',
              'Mystic River',
              'Nueve reinas',
              'Once Were Warriors',
              'True Romance',
              "Carlito's Way",
              'The Untouchables',
              'In the Heat of the Night',
              'Strangers on a Train',
              'The Big Sleep',
              'The Hateful Eight',
              'La migliore offerta',
              'The Girl with the Dragon Tattoo',
              'Madeo',
              'Män som hatar kvinnor',
              'Drive',
              'Lilja 4-ever',
              'Hana-bi',
              'A Bronx Tale',
              'Boyz n the Hood',
              'Mississippi Burning',
              'The Day of the Jackal',
              'À bout de souffle',
              'Wind River',
              'Death Note: Desu nôto',
              'This Is England',
              'Zodiac',
              'Crash',
              'Road to Perdition',
              "Ocean's Eleven",
              'Training Day',
              'Primal Fear',
              'Glengarry Glen Ross',
              "Miller's Crossing",
              'Der Name der Rose',
              'Victoria',
              'Leviafan',
              'Inside Man',
              'Gone Baby Gone',
              "Dead Man's Shoes",
              '21 Grams',
              'Boksuneun naui geot',
              'Lola rennt',
              'Funny Games',
              'Sleepers',
              'The Godfather: Part III',
              'Blood Simple',
              'The 39 Steps'],
             ' Drama': ['The Godfather',
              'The Dark Knight',
              'The Godfather: Part II',
              '12 Angry Men',
              'The Lord of the Rings: The Return of the King',
              'Pulp Fiction',
              "Schindler's List",
              'The Lord of the Rings: The Fellowship of the Ring',
              'The Lord of the Rings: The Two Towers',
              'Goodfellas',
              'Hamilton',
              'Gisaengchung',
              'Interstellar',
              'Cidade de Deus',
              'The Green Mile',
              'La vita è bella',
              'Se7en',
              'The Silence of the Lambs',
              'Seppuku',
              'Shichinin no samurai',
              'Joker',
              'The Intouchables',
              'The Departed',
              'The Pianist',
              'Gladiator',
              'Léon',
              'The Lion King',
              'Hotaru no haka',
              'Modern Times',
              'City Lights',
              'Ayla: The Daughter of War',
              'Vikram Vedha',
              'Kimi no na wa.',
              'Dangal',
              'Avengers: Endgame',
              '3 Idiots',
              'Oldeuboi',
              'Once Upon a Time in America',
              'Tengoku to jigoku',
              'Witness for the Prosecution',
              'The Great Dictator',
              'Andhadhun',
              'Drishyam',
              'Inglourious Basterds',
              'Braveheart',
              'Reservoir Dogs',
              'Amadeus',
              'Scarface',
              'Das Boot',
              'Taxi Driver',
              'The Sting',
              'A Clockwork Orange',
              'Lawrence of Arabia',
              'The Apartment',
              'Double Indemnity',
              'The Kid',
              'Chhichhore',
              'Uri: The Surgical Strike',
              'K.G.F: Chapter 1',
              'Green Book',
              'Three Billboards Outside Ebbing, Missouri',
              'Talvar',
              'Baahubali 2: The Conclusion',
              'Drishyam',
              'Queen',
              'Bhaag Milkha Bhaag',
              'Warrior',
              'The Wolf of Wall Street',
              'V for Vendetta',
              'Rang De Basanti',
              'Der Untergang',
              'A Beautiful Mind',
              'L.A. Confidential',
              'Eskiya',
              'Heat',
              'Casino',
              'Dom za vesanje',
              'Ran',
              'Raging Bull',
              'The Message',
              'The Great Escape',
              'To Kill a Mockingbird',
              'Yôjinbô',
              'Du rififi chez les hommes',
              'Rashômon',
              'The Treasure of the Sierra Madre',
              'The Gold Rush',
              'Koe no katachi',
              'Contratiempo',
              'Haider',
              'Logan',
              'Relatos salvajes',
              'PK',
              'OMG: Oh My God!',
              'Ôkami kodomo no Ame to Yuki',
              'Hacksaw Ridge',
              'Barfi!',
              '12 Years a Slave',
              'Rush',
              'Ford v Ferrari',
              'Spotlight',
              'Song of the Sea',
              'Zindagi Na Milegi Dobara',
              'Prisoners',
              'A Wednesday',
              'Harry Potter and the Deathly Hallows: Part 2',
              "Hachi: A Dog's Tale",
              'Mary and Max',
              'Into the Wild',
              'No Country for Old Men',
              'Lage Raho Munna Bhai',
              'Hotel Rwanda',
              'Taegukgi hwinalrimyeo',
              'Munna Bhai M.B.B.S.',
              'Salinui chueok',
              'Dil Chahta Hai',
              'Kill Bill: Vol. 1',
              'Catch Me If You Can',
              'Shin seiki Evangelion Gekijô-ban: Air/Magokoro wo, kimi ni',
              'Lagaan: Once Upon a Time in India',
              'The Truman Show',
              'Fargo',
              'Underground',
              'La haine',
              'Chung Hing sam lam',
              'In the Name of the Father',
              'Dead Poets Society',
              'Stand by Me',
              'Fitzcarraldo',
              'The Elephant Man',
              'Barry Lyndon',
              'Zerkalo',
              'Paper Moon',
              'Le samouraï',
              'Cool Hand Luke',
              'Andrei Rublev',
              'Inherit the Wind',
              'Les quatre cents coups',
              'Ben-Hur',
              'Kakushi-toride no san-akunin',
              'The Bridge on the River Kwai',
              'On the Waterfront',
              'Le salaire de la peur',
              'White Heat',
              'The Shop Around the Corner',
              'Mr. Smith Goes to Washington',
              "La passion de Jeanne d'Arc",
              'Badhaai ho',
              'Togo',
              'La La Land',
              'Lion',
              'The Martian',
              'Bãhubali: The Beginning',
              'Kaguyahime no monogatari',
              'Special Chabbis',
              'The Imitation Game',
              'Blade Runner 2049',
              'Bohemian Rhapsody',
              'The Revenant',
              'Tropa de Elite 2: O Inimigo Agora é Outro',
              "The King's Speech",
              'Yip Man',
              'Nefes: Vatan Sagolsun',
              'Tropa de Elite',
              'Persepolis',
              'Dallas Buyers Club',
              'The Pursuit of Happyness',
              'Blood Diamond',
              'Bin-jip',
              'Le scaphandre et le papillon',
              'Mar adentro',
              'Cinderella Man',
              'Kal Ho Naa Ho',
              'Mou gaan dou',
              'Big Fish',
              'Yeopgijeogin geunyeo',
              'Dogville',
              'Vizontele',
              'Dancer in the Dark',
              'The Straight Story',
              'Secrets & Lies',
              'Bound by Honor',
              'Dances with Wolves',
              'Do the Right Thing',
              'Tenkû no shiro Rapyuta',
              'Gandhi',
              'Being There',
              'Dog Day Afternoon',
              'Papillon',
              'Butch Cassidy and the Sundance Kid',
              'The Graduate',
              'The Sound of Music',
              'Per un pugno di dollari',
              'La dolce vita',
              'Rio Bravo',
              'Anatomy of a Murder',
              'Touch of Evil',
              'The Killing',
              'The Night of the Hunter',
              'Les diaboliques',
              'Stalag 17',
              'Rope',
              'Out of the Past',
              'La règle du jeu',
              'Knives Out',
              'Dil Bechara',
              'Manbiki kazoku',
              'Marriage Story',
              'Hunt for the Wilderpeople',
              'Captain Fantastic',
              'Sing Street',

### Weighted Avg to Supplement Missing Meta Scores

In [125]:
ratings = dataset['IMDB_Rating'].values
votes = dataset['No_of_Votes'].values
dataset['Weighted_Avg'] = (ratings * votes + votes.min() * ratings.mean()) / (votes + votes.min())
dataset.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Weighted_Avg
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469,9.285691
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411,9.180931
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444,8.988679
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000,8.977178
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000,8.963129

### Dataset describe

In [126]:
dataset.describe()

,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross,Weighted_Avg
count,1000.000000,1000.000000,843.000000,1.000000e+03,1.000000e+03,1000.000000
mean,122.891000,7.949300,77.971530,2.736929e+05,5.653688e+07,7.957808
std,28.093671,0.275491,12.376099,3.273727e+05,1.032382e+08,0.242824
min,45.000000,7.600000,28.000000,2.508800e+04,0.000000e+00,7.611562
25%,103.000000,7.700000,70.000000,5.552625e+04,4.457098e+05,7.799293
50%,119.000000,7.900000,79.000000,1.385485e+05,1.070275e+07,7.913042
75%,137.000000,8.100000,87.000000,3.741612e+05,6.153989e+07,8.077983
max,321.000000,9.300000,100.000000,2.343110e+06,9.366622e+08,9.285691

## ML stuff